"""empty message

Revision ID: c1b44fa4bdc7
Revises: 1a234963b83a
Create Date: 2018-11-03 10:32:24.440439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b44fa4bdc7'
down_revision = '1a234963b83a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('num_experiments', sa.Integer(), default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'num_experiments')
    # ### end Alembic commands ###
